# Generated by Django 5.2 on 2025-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "room_number",
                    models.IntegerField(
                        choices=[
                            (1, "Kamar 1"),
                            (2, "Kamar 2"),
                            (3, "Kamar 3"),
                            (4, "Kamar 4"),
                            (5, "Kamar 5"),
                            (6, "Kamar 6"),
                            (7, "Kamar 7"),
                            (8, "Kamar 8"),
                            (9, "Kamar 9"),
                            (10, "Kamar 10"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
