version: "3"

services:
  app:
    build: .
    container_name: taskweb-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: taskweb-redis
    ports:
      - "6379:6379"
